name: Build nodejs image and push to GutHub Container Registry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        USER_NAME: ${{ github.actor }}   
        CR_PAT: ${{ secrets.PAT }}  
      run: |
        echo $CR_PAT | docker login ghcr.io -u USER_NAME --password-stdin
                
    - name: build the Docker image
      run: docker build . --file Dockerfile -t ghcr.io/zina-420001498/nodejs:1.0.0

    - name: docker push
      run: |
        docker push ghcr.io/zina-420001498/nodejs:1.0.0
